project:
  type: website

website:
  title: "Unified Branding"
  
  bread-crumbs: true
  
  repo-url: https://github.com/posit-dev/brand-yml/
  repo-actions: [issue, source]

  navbar:
    left:
      - text: Overview
        href: index.qmd
      - text: brand.yml
        href: brand/index.qmd
      - text: "Examples"
        href: examples/index.qmd

  sidebar:
    - id: brand-yml
      contents:
        - text: Design Goals
          href: index.qmd
        - brand/open-questions.qmd
        - text: "----"
        - text: Structure
          href: brand/index.qmd
        - section: Brand Elements
          contents:
          - brand/meta.qmd
          - brand/logo.qmd
          - brand/color.qmd
          - brand/typography.qmd
          - brand/template.qmd
    - id: examples-brands
      title: Example Brand Guidelines
      contents: "examples/brand-guidelines/*/index.qmd"

format:
  html:
    theme: [bootstrap, "posit-theme.scss"]
    toc: true

lightbox: auto

editor:
  render-on-save: true

